### ISSUE TITLE
Can not install scm-ssh-plugin with scm 1.46

### ISSUE THREAD

**Issue by mcassuto** [litesolutions/scm-ssh-plugin#1]
when uploading the module into SCM 1.46 plugin manager, the uploading process ends up with message "Plugin installation failed"

**Comment by sargue** [comment]
I can't reproduce it.

I've downloaded a fresh standalone SCM Manager 1.46, executed, installed the plugin, restarted the SCM Manager, and it works.

Maybe this is related:
https://bitbucket.org/sdorra/scm-manager/issues/745/git-ssh-key-authentication-plugin-to-scm

**Comment by turtle-bazon** [comment]
I can confirm. It doesn't installs.

**Comment by turtle-bazon** [comment]
My server configuration - Debian 8 jessie with latest updates, default java on debian (1.7)
`root@scm:~# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)`

**Comment by sargue** [comment]
Can you please try Oracle JRE? It is the [recommended one](https://bitbucket.org/sdorra/scm-manager/wiki/getting-started).

**Comment by turtle-bazon** [comment]
Oracle JDK is non-trivial to install and has problems with periodic updating. SCM Manager itself works fine with OpenJDK. Also OpenJDK is very similar to OpenJDK because both developed by Oracle. Only thing is missed several components. For debugging I need logs to decite try to Oracle JDK or not, because I think that chaning JDK will not change anything.

**Comment by mcassuto** [comment]
I confirm my java version: 

# java -version

java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

Still unable to install.
Also, I would not take the risk to install OracleJDK since I have other Java apps running on this server.

@sargue did you try to reporduce using openJDK ?

**Comment by sargue** [comment]
I have reproduced it using OpenJDK 8 (latest on Debian). The error reported is exactly the same reported on this other issue:

https://bitbucket.org/sdorra/scm-manager/issues/745/git-ssh-key-authentication-plugin-to-scm

The bug is still open. Not sure if the bug is on the plugin or the main product. Anyway I didn't write the plugin nor mantain it anymore so I am sorry I can't help you.
